"""Add call_stats table for quality monitoring

Revision ID: fb958ba03c93
Revises: 9044ba1e3377
Create Date: 2025-12-04 23:40:16.951172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb958ba03c93'
down_revision: Union[str, None] = '9044ba1e3377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_id', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('audio_bitrate_kbps', sa.Float(), nullable=True),
    sa.Column('audio_packets_lost', sa.Integer(), nullable=True),
    sa.Column('audio_packets_sent', sa.Integer(), nullable=True),
    sa.Column('audio_jitter_ms', sa.Float(), nullable=True),
    sa.Column('video_bitrate_kbps', sa.Float(), nullable=True),
    sa.Column('video_packets_lost', sa.Integer(), nullable=True),
    sa.Column('video_packets_sent', sa.Integer(), nullable=True),
    sa.Column('video_frame_rate', sa.Float(), nullable=True),
    sa.Column('video_resolution', sa.String(length=20), nullable=True),
    sa.Column('rtt_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.call_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_stats_call_id'), 'call_stats', ['call_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_stats_call_id'), table_name='call_stats')
    op.drop_table('call_stats')
    # ### end Alembic commands ###
